---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app local-ai
spec:
  interval: 60m
  chart:
    spec:
      # renovate: registryUrl=https://go-skynet.github.io/helm-charts/
      chart: local-ai
      version: 3.4.2
      sourceRef:
        kind: HelmRepository
        name: go-skynet
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    replicaCount: 1
    deployment:
      image:
        repository: quay.io/go-skynet/local-ai
        tag: v2.25.0-aio-cpu
      env:
        - name: debug
          value: true
    resources:
      requests:
        gpu.intel.com/i915: 1
      limits:
        gpu.intel.com/i915: 1

    models:
      forceDownload: false
      list:
        - url: "https://gpt4all.io/models/ggml-gpt4all-j.bin"

    persistence:
      models:
        enabled: true
        annotations: {}
        storageClass: ceph-block
        accessModes: ["ReadWriteOnce"]
        globalMount: /models

      output:
        enabled: true
        annotations: {}
        accessModes: ["ReadWriteOnce"]
        storageClass: ceph-block
        globalMount: /tmp/generated

    service:
      type: LoadBalancer
      ports:
        http:
          port: 8080

    ingress:
      enabled: true
      ingressClassName: internal
      annotations:
        external-dns.alpha.kubernetes.io/target: internal.ktmb1.net
      hosts:
        - host: &host local-ai.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
