---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-ai-models
  namespace: ai
  labels:
    app.kubernetes.io/name: &name local-ai
    app.kubernetes.io/instance: *name
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: ceph-block
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-ai-output
  namespace: ai
  labels:
    app.kubernetes.io/name: &name local-ai
    app.kubernetes.io/instance: *name
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: ceph-block
  resources:
    requests:
      storage: 5Gi
