---
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: dragonfly
spec:
  authentication:
    passwordFromSecret:
      name: dragonfly-secret
      key: password
  labels:
    dragonflydb.io/cluster: dragonfly
  image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.27.3@sha256:bfd7551d10b9ce793c1e0266630cbad3e844f0c8caa27c2f8df30049313cd4f3
  replicas: 3
  args:
    - --maxmemory=$(MAX_MEMORY)Mi
    - --proactor_threads=2
    - --cluster_mode=emulated
    - --lock_on_hashtags
  env:
    - name: MAX_MEMORY
      valueFrom:
        resourceFieldRef:
          resource: limits.memory
          divisor: 1Mi
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 512Mi
  serviceSpec:
    type: LoadBalancer
    annotations:
      lbipam.cilium.io/ips: 192.168.8.102
      external-dns.alpha.kubernetes.io/hostname: redis.${SECRET_DOMAIN}
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: "kubernetes.io/hostname"
      whenUnsatisfiable: "DoNotSchedule"
      labelSelector:
        matchLabels:
          app.kubernetes.io/part-of: dragonfly
