---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: esphome
spec:
  refreshInterval: 4h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: esphome-secret
    template:
      engineVersion: v2
      data:
        USERNAME: "{{ .USERNAME }}"
        PASSWORD: "{{ .PASSWORD }}"
        ESPHOME_DASHBOARD_USE_PING: "{{ .ESPHOME_DASHBOARD_USE_PING }}"
  dataFrom:
    - extract:
        key: esphome
