---
apiVersion: v1
kind: ConfigMap
metadata:
  name: netbox-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: netbox
        group: applications
        url: http://netbox.default.svc.cluster.local
        interval: 1m
        ui:
          hide-url: true
          hide-hostname: true
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: pushover
