---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: diyhue
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
    controllers:
      diyhue:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: |
              [{
                "name":"multus-iot",
                "namespace": "network",
                "ips": ["192.168.2.39/24"],
                "mac": "aa:f8:38:83:3c:e9"
              }]
        containers:
          app:
            image:
                repository: docker.io/diyhue/core
                tag: master-488a373ea7696a77e7297c4b26a372d9b4771488
            env:
              - name: IP
                value: 192.168.2.39 # Important!!! Must be the service external IP
              - name: DEBUG
                value: "false"
              - name: MAC
                value: aa:f8:38:83:3c:e9 # Important!!! Hue app will not pair is is wrong specified. Must be host interface mac
              - name: TZ
                value: Australia/Sydney
            resources:
              requests:
                memory: 512Mi
              limits:
                memory: 1Gi
    service:
      main:
        controller: diyhue
        ports:
          http:
            port: 80
            protocol: TCP
            targetPort: 80
          https:
            port: 443
            protocol: TCP
            targetPort: 443
          hue:
            port: 2100
            protocol: UDP
            targetPort: 2100
    ingress:
      main:
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.ktmb1.net
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
        hosts:
          - host: hue.ktmb1.net
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: 80
    persistence:
      data:
        existingClaim: "${VOLSYNC_CLAIM}"
        advancedMounts:
          diyhue:
            app:
              - path: /opt/hue-emulator/config
