---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: awx
        group: applications
        url: https://awx.alexeym.net
        interval: 1m
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: pushover
