apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:FL/1Vg764FYyKCZdQEjW/HC2xIymhz0zyP3FvBIBups=,iv:Kq8YEZCTqz5hjNXVP+EIqdxHHiuRRAlGy2G81NATxpg=,tag:bfNkpoo2OFCMtinfTrt3ug==,type:str]
    credentials.json: ENC[AES256_GCM,data:PAFrZVmorsq4YJ05hBjXMxS9MEnXB0rRpWICRUgiybvaPdFtcR2AnprVpVeZ83R2tq+lwBOuycRaSIArdBUCVYTkv3O6FIhVOmbdr4oabPYm3/DPknGxajEQbCYuO0NESjQvokojcgDa60nOI4wpOZS5WxE9joYN/HHwkQ5B19t01qU5X07CGMwHBtCQGm+YCro8YzyofxFGeDTR2U3yZuQkOJ17WvXxdhjy,iv:BOo2bOKLK/SMo3xq5qa/pBiQL2pSj/PC8tIPQQ8YVfs=,tag:D9/rRZEnBhJBmWaZMfvTXw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4ep3d9r4u4mfv9268ch7nqck3favp35mfg9rqggy26gnfh6653svjah5t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQTJIbFV1SE9tZ1dEbmph
            VE9uZkNDS0ZMV2k0cTh0L0FOeDYwejZXU0hvCkcwVHZQbjIrNkRLRzREZUtmZS8y
            aHhwZlJXNXdBYlBLNFEyUk4zNXR4RWsKLS0tIFk5YVR2VFVCZG54aEFpbkphd3Rh
            RGhXY0tGNWZEWk9yYTAyTVEvU1hQSncKn0xOGw+qp74JYMdmBUnA0l01v/0NYXlV
            /8wupOaEIEnqU3NiTGTwjaZHJwHY9Isvpu68QBQwGIclPxbxvm3GlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-07T07:15:57Z"
    mac: ENC[AES256_GCM,data:5czEEhLfzU5elZOl/442EZSeDW2zRgrldYVo11jf1CnC91XUKBD1K+Gue5h0qgGeMuZoPGoDAxXPPPoeS8z3MjIgUCfcsee3M5Be30hWQBcxLIxb74Mk3ESDJ6YLjbXumU0SgjdNWsJ/xmLdROdb5PdMHUuS5KDZ5wagXwa7Kl4=,iv:Fj220fx9SUAnm/MbCIWivXYgcXWc33znYqLNKzEpwI0=,tag:QTLQBXLVGNHeMqE3Rd32ug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
