apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:lCPSt0phGai3b1LTHP9Qz0eNGwtZLN3vIHvyL3IUdO8NOYOb,iv:zd3MBP8YIuZ4q5Lbl09980k4kVC6OLxBhW5Sfd3ltus=,tag:/tgMScQi/qCGS4ixXypmPQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:3Je+FLf/5b9ADzYclAtgZHXmmZp37InVpWJ4Mk7uqJSXrNRhQeSTFDOk3WrszF9j9uk1GECNVeTMwpXqMKyCqzYi/OcOB7L8pBcXRsUnulIZC+k66s17m9qCP5N3AkVTAzCyf85hGnePNNPG0Jemn6wy89anreFvLwlgx/GrAwyJCRHF33x0Zn62WMn/nN5Coh8dqro0NafSVkeXWAd10osT4hbzcJAQGjm4oEEqAA==,iv:N4J/DwAVX9yl8l21gArTac7IKQRKu7gS5kuRxY4xyqM=,tag:vvB6z6MQVH1M/pPOpIOi5Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlz8mrty9s0u7z5we2ak4mjyc7srf7u8tp0xe8rc2u559fpe4ajsw5n5rs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBS2NxS1lwakVINHBRTk1C
            L2lvajVwTUoxdUpZWk1JdnpnRXlkWjVTMWxnCmtKbzNaU2RHZEo4UVExUnN4MElT
            VzFtZFZ2azFCZkl4b2UxVlVBUjVwRXcKLS0tIFBLTm9IRVZyVFAyYWdNTUlSdnQ5
            U2tLQUQ5Nktpd3kxUXk0VkUxWWpWN00K2DFw42n+4zh8jutQwAzhVbYjHUtKJGwG
            v1dLpT1PEz4n8Shvx16lDOHaiJLYxZqEwrBHsjEK+8oU5sZMSjmBwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-18T14:48:34Z"
    mac: ENC[AES256_GCM,data:4rNWHuzftWRmr1Lidggw4Ew7hZKivKRiajKXhkatA6lsl5FSEKMyA4u+FsCp8F9E/TnyrZSGVG9Vo2oz5jgnVk3/7diH1W6lYCL/JD+VqQZRCNF4I3kWPeKX2ppYu9l66h3jlgHNX2cIGTi+yOWDBBFAbiABr34WIgdwysGMG1g=,iv:kXUibpfBBg4neZAYm/P+7H+YjVt0+Nx870QAXdhfAlE=,tag:zs0MUFNdA0E4BgjbTS0RqQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
