apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:M8dyECih84CBvZSMHv2OXFpc9az+wZZRGlXaY9ekRsr6L5xS,iv:1EGLrq/Ad97PnCXdZz/i0q9WWsF35c/8LGFLyKwAQh4=,tag:zDpN8yq7UqK3slKgStdiOA==,type:str]
    credentials.json: ENC[AES256_GCM,data:qkAzpipSnwcCvlF8J28mUMm7pt90OcdIsCkn1ZrX+wzg8Wu1PcmV8CNlKJXS1gp+Oe2cG6aqAJj1n8HZV/C/TirqoSrRewhi+h6kSl0aSGMftcObYMG8+/jrOJ22HOVw6xLfyc5h/EczOk2sTCE2u9kiddgHcf7ZxmAMbH1rPZyn2GNc0yoPlB+aUCKoz4Q+Av7vXDcqW2FM6hZrGELn3PLkHTQ36fMl2owNYTB/CA==,iv:PqIFk+htoV42EHOYoQHO2xkbi6gcWvsSdgVftN/fOVg=,tag:kBqiA5tXXG4jNEERypsblg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4ep3d9r4u4mfv9268ch7nqck3favp35mfg9rqggy26gnfh6653svjah5t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNm12NUw1dFJ3SWNBUWNk
            elZrT0dNdy8rOEdoSERYUTI1d0JvWEVUeFhNCmovKzJBR0d6aDFZZk9TSzZhc0VO
            ME8xQ2JJU2pQVVk4c1JnMEorcU52bE0KLS0tIDltd0R2MldJVnF3OGpaUkpWeVdF
            WXdVZEp3aHpRWTRmZHBYeVNlRUlEQ28K7MJXerbQV+ZB2J1vmnxavd0G1pRqL8OS
            rlDsf9/0Opf+NfoRnmTJKSizhuzucz5lWfPRD9TBcEk5rLAD/S+uJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-07T09:05:37Z"
    mac: ENC[AES256_GCM,data:XEOhhppqHypo0cjN/Zitp7Gl/O4s7u/b4Hzc1snsJ/JEfc72Gh86UYSlJemdmCLrD8BwCSytmbbmBaTt14x3zUBCOXTT9n6SuriwO9iGXrc60Lo0A2FA/V0bPFyZik5GTnPkcuMOr+em99zjmT9F5t1a5dMiKqr0F2NfQTvI1wE=,iv:Fbgz57oOu9n2AnIVGIzFsJDeqrBJJUsHQNo+Cjkwaz8=,tag:QfYidFim2rDR0d0TVPztGw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
