---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: authentik-secret
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: AUTHENTIK_POSTGRESQL__USER
      remoteRef:
        key: authentik
        property: authentik.AUTHENTIK_POSTGRESQL__USER
    - secretKey: AUTHENTIK_POSTGRESQL__PASSWORD
      remoteRef:
        key: authentik
        property: authentik.AUTHENTIK_POSTGRESQL__PASSWORD
    - secretKey: AUTHENTIK_POSTGRESQL__NAME
      remoteRef:
        key: authentik
        property: authentik.AUTHENTIK_POSTGRESQL__NAME
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: authentik
        property: authentik.AUTHENTIK_SECRET_KEY
    - secretKey: AUTHENTIK_POSTGRESQL__HOST
      remoteRef:
        key: authentik
        property: authentik.AUTHENTIK_POSTGRESQL__HOST
    - secretKey: INIT_POSTGRES_DBNAME
      remoteRef:
        key: authentik
        property: authentik.AUTHENTIK_POSTGRESQL__NAME
    - secretKey: INIT_POSTGRES_HOST
      remoteRef:
        key: authentik
        property: authentik.AUTHENTIK_POSTGRESQL__HOST
    - secretKey: INIT_POSTGRES_USER
      remoteRef:
        key: authentik
        property: authentik.AUTHENTIK_POSTGRESQL__USER
    - secretKey: INIT_POSTGRES_PASS
      remoteRef:
        key: authentik
        property: authentik.AUTHENTIK_POSTGRESQL__PASSWORD
    - secretKey: AUTHENTIK_INSECURE
      remoteRef:
        key: authentik
        property: authentik.AUTHENTIK_INSECURE
    - secretKey: INIT_POSTGRES_SUPER_USER
      remoteRef:
        key: cloudnative-pg
        property: postgres.username
    - secretKey: INIT_POSTGRES_SUPER_PASS
      remoteRef:
        key: cloudnative-pg
        property: postgres.password
    - secretKey: AUTHENTIK_HOST
      remoteRef:
        key: authentik
        property: authentik.AUTHENTIK_HOST
    - secretKey: AUTHENTIK_TOKEN
      remoteRef:
        key: authentik
        property: authentik.AUTHENTIK_TOKEN
    - secretKey: AUTHENTIK_STORAGE__MEDIA__BACKEND
      remoteRef:
        key: authentik
        property: authentik.AUTHENTIK_STORAGE__MEDIA__BACKEND
    - secretKey: AUTHENTIK_STORAGE__MEDIA__S3__ACCESS_KEY
      remoteRef:
        key: minio
        property: aws-access-key-id
    - secretKey: AUTHENTIK_STORAGE__MEDIA__S3__SECRET_KEY
      remoteRef:
        key: minio
        property: aws-secret-access-key
    - secretKey: AUTHENTIK_STORAGE__MEDIA__S3__BUCKET_NAME
      remoteRef:
        key: authentik
        property: authentik.AUTHENTIK_STORAGE__MEDIA__S3__BUCKET_NAME
    - secretKey: AUTHENTIK_STORAGE__MEDIA__S3__ENDPOINT
      remoteRef:
        key: authentik
        property: authentik.AUTHENTIK_STORAGE__MEDIA__S3__ENDPOINT
    - secretKey: AUTHENTIK_STORAGE__MEDIA__S3__CUSTOM_DOMAIN
      remoteRef:
        key: authentik
        property: authentik.AUTHENTIK_STORAGE__MEDIA__S3__CUSTOM_DOMAIN
