---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: minio-secret
    template:
      engineVersion: v2
      mergePolicy: Merge
      data:
        # App
        MINIO_ROOT_USER: "{{ .MINIO_ROOT_USER }}"
        MINIO_ROOT_PASSWORD: "{{ .MINIO_ROOT_PASSWORD }}"
  dataFrom:
    - extract:
        key: minio
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-restic-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: minio-restic-config
    template:
      engineVersion: v2
      mergePolicy: Merge
      data:
        RESTIC_REPOSITORY: "{{ .CLUSTER_RESTIC_REPOSITORY }}/minio-pvc-backup"
  data:
    - secretKey: CLUSTER_RESTIC_REPOSITORY
      remoteRef:
        key: minio
        property: RESTIC_REPOSITORY
    - secretKey: RESTIC_PASSWORD
      remoteRef:
        key: minio
        property: RESTIC_PASSWORD
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: minio
        property: backup-aws-access-key-id
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: minio
        property: backup-aws-secret-access-key
