---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: s3 storage
        group: applications
        url: http://minio.default.svc.cluster.local:9001
        interval: 1m
        ui:
          hide-url: true
          hide-hostname: true
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: pushover
