---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: s3 storage
        group: infrastructure-services
        url: https://minio.alexeym.net
        interval: 1m
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: pushover
