---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana
spec:
  refreshInterval: 4h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: grafana-secret
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: teslamate_dbpass
      remoteRef:
        key: teslamate
        property: POSTGRES_PASS
    - secretKey: homeassistant_dbpass
      remoteRef:
        key: cloudnative-pg
        property: POSTGRES_SUPER_PASS
    - secretKey: admin-user
      remoteRef:
        key: grafana
        property: GRAFANA_ADMIN_USERNAME
    - secretKey: admin-password
      remoteRef:
        key: grafana
        property: GRAFANA_ADMIN_PASSWORD
    - secretKey: oauth_client_id
      remoteRef:
        key: grafana
        property: GRAFANA_OAUTH_CLIENT_ID
