apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:5jrrFgSjvkArKmzVOQFvcRZbR3fH4DGvyH2NuY8MrT+dGGOpe3z9vw==,iv:+I2l011X+DB5bv5nsFSCpVlVh/bPcDK3m0XDg3o9GxQ=,tag:ApV/HFa2jolM3h4zDbcltQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4ep3d9r4u4mfv9268ch7nqck3favp35mfg9rqggy26gnfh6653svjah5t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZL0xYcUNsdGNObThjOWhO
            MzJYZm95VkxXb01vekhRcWFTRldZd001NkdJCk51TVZzeTRFQXgwVlNEY0dFUXd5
            cXM3aVd4K09RM01oQUNQNndKWW1PMTAKLS0tIEFDN3puejFsaVZBTk1FRlhkOFI0
            ZWI0SFdYczdWZ0czcHlXTll6cDNjQUkK2Zjff+HzuCgSwN7MbS5NyYBHOU4SV5uJ
            faJIjeVfkj+3xPneKRfHF4B2Ocr4q4hFidSdYpr95wLjG5bPuPAfVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-07T09:05:37Z"
    mac: ENC[AES256_GCM,data:Bi93b30HTpwLKKggPDXYQ0dPXQzX5yIe1tgaCLiobCF9o+hw+3kNEXGLhE51D6/tQBQvAathHQZRetnlt/VZw/Y90jsb+6W5VZjXZ8VrQN6KBjMmkVAshIkOsNOxCiBtDwsxiCzQeIu1zc8jXcJgkhIRh21LGmIyPQDuKTBSI2s=,iv:VFwYAibZzoL4kq/GaOJLT/xBex3WErdjyuXmK5G4ohU=,tag:qUE/Mo3T1FcV41dHOg+kyw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
