# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Cw9FSamqFZbcn0YsC5bh7PDtJocEB/hfwvh4wdf/WwjqJy9B3a6ETQ==,iv:4z1emdAPk6pXIRkr+VRO98+4zZwVBRupLHVCF3BHnEM=,tag:DQgGhF94HUjnELV9SOmCFA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14maqe2lw00kmdc0z7ulr8al7gwwz4wxgyltn8pd7h897wtakk98qlztlpn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByRnNhcFZ4ajR5OUNheHps
        OVVtUnkrdm9KVGREVEFIblZEYmtCU204WHhnCjFUWUNGUVNNVkpKSEUrY012Rmgw
        VXhOcENNR3hvU2tvV0dIYzM2c2t3SWMKLS0tIDUyUTZqUFU4dUR5cW5nSWVWVkxS
        NjB2VU16eEE0RlBYZVhzSGhoSjVJNDAKZXhOokCApLizTwFMDakkiZqlAT0v09p7
        fRG6ED/0fFG1nn7YQaMrHniCv20C4YzvaaBDUeO4dYOxsAKUEEHTRw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-13T05:18:45Z"
  mac: ENC[AES256_GCM,data:n3ypID8fYYAjv+5+E6LFmuGICbf2DC7f6185uryXvdw805NG/mBtLmIPIrqjbausJgdUsLZRraLCb7CO9pJCWLnxdAOw5dV41XkfA6yiLMwqKscZ97cQSsu8c+9sv/cf4m9eCrxpF3/ikQ3ESc9dZp7uQcmJEU2pxJfMYK0rXX0=,iv:LLKmhnvDKYT8Hts2tBwKXPlohihVzfOfPgiaGTn8/PQ=,tag:egWT6v4Y433jHp2uG0/hwg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
