apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:nEkMjsSjuDe0Z3uDbh6sNjZAu1e4aCfFsdJKD3fK8Hcd9qIupm64Ww==,iv:b+nv3oK9pVihM9XC6kEUTxNHav+b45jJ39M+p99UguM=,tag:DzohzX16WpxjQ0qT+RKZXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlz8mrty9s0u7z5we2ak4mjyc7srf7u8tp0xe8rc2u559fpe4ajsw5n5rs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1R3Q0RzJtckVmNVdaVCts
            ZWFMY3BSTnI5STdWMkJmRHpoeTc1bU5FMkFJCnZrZ2hyclovOTBBWVFZR3hGeEEr
            QTVLOUdpSTBheGFsaVZHWjRCcXJ3eEkKLS0tIGxtODBWYzlzbHBVejZKQ3FNdXEx
            WFkwR2tvK1hBMVZkZVFpSmZjcktIbFkKyyIWSETnhjIMI2lLYMOsgy4JnIX3fB8q
            ykxeKoHQ6Xm2ofUurTVpUHcD6DmK7AaByggT3/eGutGDB4Pf+stPSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-18T14:48:34Z"
    mac: ENC[AES256_GCM,data:jx9V9GD5ZNjDldY7fUzzK6Iyuj+qekBKH6IhBJ+/fw8EQy7NIDnHnTUx20gu58GttcTsaZ2qZ//j06Js5TgMfbtjlKo13FbmULDe4DbhsQMCZlxlL6s7k+ZbNrYIMg65UB/M41PrC+/D0cPNWSkYpT93H/AyGN/Q0RtHUDq/Pd0=,iv:G9FmkhZa7jPSbsPOJZE+oQO3PXAFJGBqlRwHdohaSuI=,tag:fjWHasBqOQpN7N5q7e03fg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
