apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:81DNWt93nqzJ9HB/V0tO0MwDR2UTzvdQY/1bfrOmrtITLssqMz9zMA==,iv:YpcKtmzF2aBb55IPz2ctSfMItDLsSVQdNE/gZ9XgWCc=,tag:mdaX0hJYzHcCfX7ZbbjdcA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4ep3d9r4u4mfv9268ch7nqck3favp35mfg9rqggy26gnfh6653svjah5t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtMWR0dWZIUTMvNE1HVFZn
            WnNYU2xmUlp3bmh4ZndZYStncmNqVGVlbDBFCnQvbm5ORlM1RnFYY2RJcS81UmFP
            a1RGNGpPQVJGR1VCenB0aEJLaWViQ2MKLS0tIHczTDRubUZPbUxWZVp1YStZMWlK
            L1MzZDk3RWRPa3NHQ3NxcFdZeDBmbU0K9j6Z9fuk6IXsBpNiNEJxGeTG0Sk/aOhi
            R+EyqMe8COp54f0IgcHbn52i/gSnF0IuQgqhUMlawEv9+TzpPFXPMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-09T04:21:46Z"
    mac: ENC[AES256_GCM,data:y1vdFneNl2G07GX4woBveAANCt0O5ULTQpm+DkZA6JQOYjKadO3LWoNUTtJWA1pHB7XJforsZS3h3jRzuWQbaj9IlZqQdlE+PXoiUflHvoUdipZv3YhP8Q2ummvU4/rKGiTR3fzDox7c2/UZQI9ExiRGu+/TwclJJd+b9/K3Ufo=,iv:BV5oEIzIDcp+UnGr2ww+A4WLWB+cgN4gDgrjZ6BJWEo=,tag:AZ5Rqa7I8wI0Uj2oiydUtQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
