---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: smtp-relay
  namespace: default
spec:
  refreshInterval: 4h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: smtp-relay-secret
    template:
      engineVersion: v2
      data:
        SMTP_RELAY_HOSTNAME: "{{ .SMTP_RELAY_HOSTNAME }}"
        SMTP_RELAY_SERVER: "{{ .SMTP_RELAY_SERVER }}"
        SMTP_RELAY_USERNAME: "{{ .SMTP_RELAY_USERNAME }}"
        SMTP_RELAY_PASSWORD: "{{ .SMTP_RELAY_PASSWORD }}"
  dataFrom:
    - extract:
        key: smtp-relay
