---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./controlplaneio.yaml
  - ./coredns.yaml
  - ./external-dns.yaml
  - ./ingress-nginx.yaml
  - ./jetstack.yaml
  - ./k8s-gateway.yaml
  - ./metrics-server.yaml
  - ./openebs.yaml
  - ./prometheus-community.yaml
  - ./spegel.yaml
  - ./stakater.yaml
  - ./angelnu.yaml
  - ./backube.yaml
  - ./bitnami-charts.yaml
  - ./cloudnative-pg.yaml
  - ./descheduler.yaml
  - ./emqx.yaml
  - ./external-secrets.yaml
  - ./grafana.yaml
  - ./intel.yaml
  - ./netbox.yaml
  - ./node-feature-discovery.yaml
  - ./piraeus.yaml
  - ./postfinance.yaml
  - ./rook-ceph.yaml
  - ./zitadel.yaml
  - ./actions-runner-controller.yaml
  - ./go-skynet.yaml
  - ./litellm.yaml
  - ./vllm-stack.yaml
  - ./open-webui.yaml
  - ./awx-charts.yaml




