---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: vllm-stack
  namespace: flux-system
spec:
  interval: 30m
  url: https://vllm-project.github.io/production-stack
  timeout: 3m
