---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: awx
spec:
  refreshInterval: 4h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: awx-secret
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
  dataFrom:
    - extract:
        key: awx
