---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: awx
spec:
  refreshInterval: 4h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: awx-secret
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
  - secretKey: database
    remoteRef:
      key: awx
      property: awx_database_name
  - secretKey: host
    remoteRef:
      key: awx
      property: awx_database_host
  - secretKey: password
    remoteRef:
      key: awx
      property: awx_database_password
  - secretKey: port
    remoteRef:
      key: awx
      property: awx_database_port
  - secretKey: sslmode
    remoteRef:
      key: awx
      property: awx_sslmode
  - secretKey: target_session_attrs
    remoteRef:
      key: awx
      property: awx_attrs
  - secretKey: type
    remoteRef:
      key: awx
      property: awx_type
  - secretKey: username
    remoteRef:
      key: awx
      property: awx_database_username
