---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: awx
spec:
  interval: 1h
  chart:
    spec:
      chart: awx-operator
      version: 3.0.0
      sourceRef:
        kind: HelmRepository
        name: awx-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    AWX:
      name: awx
      enabled: true
      spec:
        admin_user: admin
        ingress_type: ingress
        service_type: ClusterIP
        ingress_annotations: |
          external-dns.alpha.kubernetes.io/target: internal.ktmb1.net
        ingress_class_name: internal
        ingress_hosts:
          - hostname: awx.${SECRET_DOMAIN}
        hostname: awx.${SECRET_DOMAIN}
        garbage_collect_secrets: true
        no_log: false
        projects_persistence: true
        projects_existing_claim: awx
        projects_storage_class: ceph-block
        projects_storage_size: 20Gi
        postgres_configuration_secret: awx-secret
        auto_upgrade: true
      postgres:
        enabled: false
      controller: {}
      customSecrets.admin.enabled: true
      customVolumes:
        postgres:
          enabled: false
