---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nodered
spec:
  refreshInterval: 4h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: nodered-secret
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        NODE_RED_CREDENTIAL_SECRET: "{{ .node_red_credentials_secret }}"
        NODE_RED_PASSWORD: "{{ .node_red_access_password_hashed }}"
  dataFrom:
    - extract:
        key: nodered
      rewrite:
        - regexp:
            source: "(.*)"
            target: "node_red_$1"
