---
web:
  port: ${WEB_PORT}
storage:
  type: postgres
  path: postgres://${INIT_POSTGRES_USER}:${INIT_POSTGRES_PASS}@${INIT_POSTGRES_HOST}:5432/${INIT_POSTGRES_DBNAME}?sslmode=disable
  caching: true
metrics: true
debug: false
ui:
  title: Status | Gatus
  header: Status
alerting:
  pushover:
    title: Gatus
    application-token: ${PUSHOVER_TOKEN}
    user-key: ${PUSHOVER_USER_KEY}
    priority: 1
    default-alert:
      description: health-check failed
      send-on-resolved: true
      failure-threshold: 3
      success-threshold: 3
security:
    oidc:
        issuer-url: https://sso.ktmb1.net
        client-id: ${CLIENT_ID}
        client-secret: ${CLIENT_SECRET}
        redirect-url: https://status.ktmb1.net/authorization-code/callback
        scopes: [openid]
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m
endpoints:
  - name: flux-webhook
    group: external
    url: https://flux-webhook.ktmb1.net
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 404"
    alerts:
      - type: pushover

  - name: home-assistant
    group: smart-home
    url: https://homeassistant.ktmb1.net
    interval: 1m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: pushover

  - name: ktmb1-g-rt-001 (main router)
    group: network-devices
    url: https://ktmb1-g-rt-001.infra.ktmb1.net
    interval: 1m
    client:
      dns-resolver: tcp://192.168.1.1:53
      insecure: true
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: pushover

  - name: ktmb1-g-sw-001 (main switch)
    group: network-devices
    url: tcp://ktmb1-g-sw-001.infra.ktmb1.net:22
    interval: 1m
    client:
      insecure: true
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: pushover

  - name: ktmb1-g-sw-002 (CCTV switch)
    group: network-devices
    url: tcp://ktmb1-g-sw-002.infra.ktmb1.net:22
    interval: 1m
    client:
      insecure: true
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: pushover

  - name: ktmb1-t-sw-001 (office switch)
    group: network-devices
    url: tcp://ktmb1-t-sw-001.infra.ktmb1.net:22
    interval: 1m
    client:
      insecure: true
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: pushover

  - name: ktmb1-g-wap-001 (garage wireless access point)
    group: network-devices
    url: tcp://ktmb1-g-wap-001.infra.ktmb1.net:22
    interval: 1m
    client:
      insecure: true
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: pushover

  - name: ktmb1-u-wap-001 (upstairs wireless access point)
    group: network-devices
    url: tcp://ktmb1-u-wap-001.infra.ktmb1.net:22
    interval: 1m
    client:
      insecure: true
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: pushover

  - name: ktmb1-t-wap-001 (top floor wireless access point)
    group: network-devices
    url: tcp://ktmb1-t-wap-001.infra.ktmb1.net:22
    interval: 1m
    client:
      insecure: true
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: pushover

  - name: ktmb1-g-ups-002 (automatic power transfer switch)
    group: network-devices
    url: tcp://ktmb1-g-ups-002.infra.ktmb1.net:23
    interval: 1m
    client:
      insecure: true
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: pushover

  - name: ktmb1-g-srv-001 (philips hue hub)
    group: smart-home
    url: tcp://ktmb1-g-srv-001.iot.ktmb1.net:80
    interval: 1m
    client:
      insecure: true
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: pushover

  - name: gatus
    group: applications
    url: http://status.ktmb1.net
    interval: 1m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: pushover
