---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: adguard
spec:
  refreshInterval: 4h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: adguard-secret
    template:
      mergePolicy: Merge
      engineVersion: v2
      data:
        LOG_LEVEL: "info"
        AWS_ACCESS_KEY_ID: "{{ .backup_aws_access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ .backup_aws_secret_access_key }}"
        RESTIC_REPOSITORY: "{{ .RESTIC_REPOSITORY }}adguard"
  dataFrom:
    - extract:
        key: adguard
    - extract:
        key: minio
