---
apiVersion: v1
kind: ConfigMap
metadata:
  name: adguard-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: dns master
        group: infrastructure-services
        url: "udp://adguard.alexeym.net:53"
        interval: 1m
        conditions:
          - "[CONNECTED] == true"
        alerts:
          - type: pushover
      - name: dns replica
        group: infrastructure-services
        url: "udp://adguard-replica.alexeym.net:53"
        interval: 1m
        conditions:
          - "[CONNECTED] == true"
        alerts:
          - type: pushover
