---
apiVersion: v1
kind: ConfigMap
metadata:
  name: adguard-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: dns master
        group: infrastructure-services
        url: "udp://192.168.2.43:53"
        interval: 1m
        ui:
          hide-url: true
          hide-hostname: true
        conditions:
          - "[CONNECTED] == true"
        alerts:
          - type: pushover
