---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: adguard
  namespace: network
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      adguard:
        replicas: 1
        strategy: RollingUpdate

        containers:
          app:
            image:
              repository: adguard/adguardhome
              tag: v0.107.51
            env:
              TZ: "Australia/Sydney"

    service:
      app:
        controller: adguard
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 192.168.6.11
        ports:
          http:
            primary: true
            port: 80
          dns-tcp:
            port: 53
            protocol: TCP
          dns-udp:
            port: 53
            protocol: UDP

    persistence:
      data:
        existingClaim: adguard-data
        globalMounts:
          - path: /opt/adguardhome/data
      conf:
        existingClaim: adguard-conf
        globalMounts:
          - path: /opt/adguardhome/conf

    ingress:
      app:
        className: "internal"
        hosts:
          - host: &host adguard-replica.alexeym.net
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name adguard-sync
  namespace: network
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  targetNamespace: adguard
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  dependsOn:
    - name: adguard
      namespace: network
  valuesFrom:
    - targetPath: controllers.adguard-sync.containers.app.env.ORIGIN_URL
      kind: Secret
      name: adguard-secret
      valuesKey: ORIGIN_URL
    - targetPath: controllers.adguard-sync.containers.app.env.ORIGIN_USERNAME
      kind: Secret
      name: adguard-secret
      valuesKey: ORIGIN_USERNAME
    - targetPath: controllers.adguard-sync.containers.app.env.ORIGIN_PASSWORD
      kind: Secret
      name: adguard-secret
      valuesKey: ORIGIN_PASSWORD
    - targetPath: controllers.adguard-sync.containers.app.env.REPLICA1_USERNAME
      kind: Secret
      name: adguard-secret
      valuesKey: REPLICA1_USERNAME
    - targetPath: controllers.adguard-sync.containers.app.env.REPLICA1_PASSWORD
      kind: Secret
      name: adguard-secret
      valuesKey: REPLICA1_PASSWORD
    - targetPath: controllers.adguard-sync.containers.app.env.REPLICA1_URL
      kind: Secret
      name: adguard-secret
      valuesKey: REPLICA1_URL
  values:
    fullnameOverride: *name
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
    controllers:
      adguard-sync:
        containers:
          app:
            image:
              repository: ghcr.io/bakito/adguardhome-sync
              tag: v0.6.11
            args: ["run"]
            env:
              TZ: "Australia/Sydney"
              API_PORT: '0'
              CRON: '*/5 * * * *'
            resources:
              requests:
                cpu: 50m
                memory: 20Mi
              limits:
                cpu: 100m
                memory: 50Mi
