---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name meshcentral-secret
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: *name
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
      templateFrom:
        - configMap:
            name: meshcentral-config-tpl
            items:
              - key: config.json
  dataFrom:
    - extract:
        key: meshcentral
