---
apiVersion: v1
kind: ConfigMap
metadata:
  name: meshcentral-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: remote power controller
        group: applications
        url: https://meshcentral.alexeym.net
        interval: 1m
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: pushover
