apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:lciPBpE9qZInd1GytjGSfNfmY7oa28oRQaweRp1K1DTR2citwHWZXldjLqS3mB7u5UbYccK7gZZcRsvSPGN+xn2Ypu9P/jbcCZ9aXhtNb3yqWrRHrL2Ge5ChmUIRMw==,iv:RyFS+h1f6bIXArJVy2UltZaAuWi1m2nxV/KV2ne2I84=,tag:2tu7yRfj2yf0dax/L9Cpsg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:SYVrOkwM2L+Q5Js=,iv:qFUY2x78oA5qt2wkzvwaA0DE2/P+JlTQNltpiHI/NnU=,tag:hQT0JWYgwFEVrMkR3/eKfQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:vvzlVq2Fih1n9rh0h13fgmAXHeHwhy/J,iv:abIfdeT6uRj0hjBc8wv9xn/KlPwxr8v+YC7KoMi8m0Q=,tag:1v+c/TX4O5xUIBIjhRjRLw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:f5e2RwLH1hIJOmV9sAIuo2eCPa5/MWz3/d81A7dkvsc63j5l,iv:bW/42qeaZkeQDagERUaxia1/uxnx70zwC1cmtOJ3gyY=,tag:mxjCpjmjAEtG+BPvhKrZkQ==,type:str]
    SECRET_EXTERNAL_SECRETS_AWS_SSM_ROLE: ENC[AES256_GCM,data:I+SKmfW9+L0MDjXqU4k+xcti5qzCduNoS5oT45nx+QHqstNkTqXOtZpJmULcJGyiYQ2Z,iv:otT1791oaDzt+/x1QCxnzSPP9S/S04IUhpTSVM0DwmU=,tag:YbLZe7DFOQvHjCZmluwPug==,type:str]
    SECRET_EXTERNAL_SECRETS_AWS_SSM_REGION: ENC[AES256_GCM,data:xxFs5FqnFh2cgdIA9S4=,iv:b4hOhBAXQSFtI2gNWIybzxe1EBEs9ao+09feLUp37BU=,tag:K3+D1Uv8XgmD1Wel66g0rg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4ep3d9r4u4mfv9268ch7nqck3favp35mfg9rqggy26gnfh6653svjah5t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvRkRLbVlqWHNmZ21mVGx2
            UDcvclY0MXpHTXJ6OWVuMTZMSllZbzNQTUFFCkVXTWhxa3lxcm8xQm5GT2NxMlVa
            ay8wbmNvbDFCczdVNDNOMk56d3d4TnMKLS0tIEFiclh1SGIxV3hKTVVySnVESjRW
            ZDNQY3EyM0loQzZ6cXBEc0IzME41ejgKHqj7dDC2rlj4ynaXf3r5zehCMAM1jUWB
            /qCAiDKgPKSajntotPeVdHv8qs1Btqq7yY1fv9q+VYdLPdhQON8y/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-10T02:19:27Z"
    mac: ENC[AES256_GCM,data:uGu2HTrVBBRd3D/2kTE3zF4gwxLbb0uNJogGoB2dKEQRn5qBAiAgWMTkpX7LrAVmYbo7Lt5nJUI2QyC8I+G8KHvxHpdmwtmyVEwnX//qXWVtPKYzMEyWzgw0fgDSf/RgphSayr1Ims8Xgj4TLzvBFnD2ARIMWfP+sejItaVcIPs=,iv:9SCcuan1dS0PCvkULRx4cR2vAfev10RvNSyE8RlmCrw=,tag:yJz6fbr2ASDPUk1gtI2XJQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
