apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:suOBQBlY7+r6,iv:Guxe26O8zWP4Ub27eUMmVIscewF4CkvCiTVK2Cf5TGo=,tag:ugV7rM9+AdK4p46KXmhB+g==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:8/MbIJzV1yN42MzzIyNXF31X1sDMBrxg,iv:/uM3h0yUDMQz1r+nvjKqG079F181+aVhJS0wt6hg4mI=,tag:E1AjFHLdjZz9my7e7CuZcQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:G9yGyvDBRrRb4E7IJPsGCTdAqCDMImGh6zECVHbkM+Iqydy/,iv:6MUzmZNbCXVmK4OyIc9jISgv8eSJdqx6LTFCyKOX5R0=,tag:q874SepiBwZy/4x5Wwwz2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlz8mrty9s0u7z5we2ak4mjyc7srf7u8tp0xe8rc2u559fpe4ajsw5n5rs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTlQ4L2Z5QXNvWDZRSXJG
            TTY4OU94NUxFRWFRNDJtdnkxTUZ2amNQbnpVCjVRQ1lPVVBvKy9GWjNvTTNDbFRJ
            QXFmK2pMS3luTDBmQmxqdVFFT3l4VFkKLS0tIE9yeTlFOHhMVjhNdmJiNEIyMVky
            N2tSbTlsUVgwTmcyZ05SSEdUcVcrL00K/1HtQyNJSwdYSmpNMYSwWylvuDrqIpw3
            JW+wviW9pXgDK7E80Ibued6tdWm4aLtCuT9VX2Uj6/g1XKjPYndzVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-22T00:55:18Z"
    mac: ENC[AES256_GCM,data:EVQkBmGeB/I8vVBNJIb2UDgd2POdRX9OL2jV6mfl0SsIq9wxiJjoL6Q5xi+PUQRPQEuuQPIjMShRDfNYoSxf36IdoTLwHpQozvSf+raDoMid23y0t3uul3R5nE2A/kD/5x3sOrurGGf6FKgLNPg4KK2gxfyXODqx1Nw0E/t2e5g=,iv:q5yJ/3ykDXlyXCYK8kpbR/f3EfGehtTUjvDUNU7+ypI=,tag:u8vw7xcGJXaPVp0xEImEyg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
