apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:NfAFRx9JE2bs,iv:GpZmmTSyoJF+C/oUZQSlMlaD+Ay3/Z0g8I8KSdNMzQ0=,tag:8QCNIsGqMWyHZIZSy1cfEA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:Azb9rkZX9WhXHDpsoCMJEcDJmmBIYm/+,iv:zIPWLcounHY9zB31xqugyq+Qv4VfDLYhDltbDPvKDQM=,tag:qkIINzn2KHOErCol+Fe4kw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:B4CxeFTtrMID5oUAUl9OaM4ljlHxim2jvgISG85J10dJVWhC,iv:HgNP/4wufZsfnzaBxocmMDwCepimCsQfBZaXkEmpr/U=,tag:/skpldltN1F35S9VoF/y5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlz8mrty9s0u7z5we2ak4mjyc7srf7u8tp0xe8rc2u559fpe4ajsw5n5rs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Szc0VUszMnovSVdneHFr
            ZXUwbDd6TTdDc2hkVjlFTXBEZDd6cGl2b1NVCktQYXBhdWt2ZzlhMzRhWmd3QlJY
            YVNxNS9ZZXBGSUNrWTIrMDhvblAxVmcKLS0tIDI3VkF3Qnc0MHZnM2RZcThiK1Uw
            bnpkaGd2WHZMY0hrdlZpNjVpaE1LNzQKwMwsDcFWIGR1N6vgeoV9HInCCnjzSfyA
            Ir0C7eBP2WQ/p4q+5jenMOYryeeM17lbliNQV1qyqr8zscn8ssfDuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-18T14:48:34Z"
    mac: ENC[AES256_GCM,data:5xmPHs+YJQwLWtqt/0YUTO7WJ0RqVFiVcFO3JBeji8ShUu+8SjTt3aCbskmzVkzMIkJ9vJSAsujf+SMzXU9ZYp2RXI7NFnfy4ooILUnx1sqCivp/98sgLiDOmt0LORghMPLWJe7dJv4+4YEPLBI785BdhxFcVw7Gt6v4Ci2ZXNQ=,iv:hTJ6B/zdWxjc2qVBl8zzQZpMgnCQ5kruk7WJ2uhYWWU=,tag:x/3I1c+Z9PtSF7ST901iyA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
