---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: paperless-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        PAPERLESS_DBENGINE: postgresql
        PAPERLESS_DBPORT: "5432"
        PAPERLESS_DBNAME: &dbName paperless_db
        PAPERLESS_DBHOST: &dbHost postgres16-rw.database.svc.cluster.local
        PAPERLESS_DBUSER: &dbUser "{{ .PAPERLESS_DBUSER }}"
        PAPERLESS_DBPASS: &dbPass "{{ .PAPERLESS_DBPASS }}"
        PAPERLESS_ADMIN_USER: "{{ .PAPERLESS_ADMIN_USER }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .PAPERLESS_ADMIN_PASSWORD }}"
        PAPERLESS_SECRET_KEY: "{{ .PAPERLESS_SECRET_KEY }}"
        PAPERLESS_GMAIL_OAUTH_CLIENT_ID: "{{ .PAPERLESS_GMAIL_OAUTH_CLIENT_ID }}"
        PAPERLESS_GMAIL_OAUTH_CLIENT_SECRET: "{{ .PAPERLESS_GMAIL_OAUTH_CLIENT_SECRET }}"
        PAPERLESS_OAUTH_CLIENT_SECRET: "{{ .PAPERLESS_OAUTH_CLIENT_SECRET }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # Redis
        REDIS_PASSWORD: &redisPass "{{ .redis_password }}"
        PAPERLESS_REDIS: redis://:{{ .redis_password }}@dragonfly.database.svc.cluster.local:6379
  dataFrom:
    - extract:
        key: paperless
    - extract:
        key: cloudnative-pg
    - extract:
        key: redis
