---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    controllers:
      paperless:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
            envFrom: &envFrom
              - secretRef:
                  name: paperless-secret
        containers:
          app:
            image:
              repository: ghcr.io/paperless-ngx/paperless-ngx
              tag: 2.14.7
            envFrom: *envFrom
            env:
              # Configure application
              PAPERLESS_SECRET_KEY:
                valueFrom:
                  secretKeyRef:
                    name: paperless-secret
                    key: PAPERLESS_SECRET_KEY
              PAPERLESS_URL: https://paperless.${SECRET_DOMAIN}
              PAPERLESS_OAUTH_CALLBACK_BASE_URL: https://paperless.${SECRET_DOMAIN}
              PAPERLESS_PORT: &port "8000"
              PAPERLESS_TIME_ZONE: "Australia/Sydney"
              PAPERLESS_WEBSERVER_WORKERS: "2"
              PAPERLESS_TASK_WORKERS: "2"
              # Configure folders
              PAPERLESS_CONSUMPTION_DIR: /data/nas/incoming
              PAPERLESS_DATA_DIR: /data/local/data
              PAPERLESS_EXPORT_DIR: /data/nas/export
              PAPERLESS_MEDIA_ROOT: /data/local/media
              # Configure folder importer
              PAPERLESS_CONSUMER_POLLING: "60"
              PAPERLESS_CONSUMER_RECURSIVE: "true"
              PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: "true"
              # Configure OCR
              PAPERLESS_OCR_LANGUAGES: eng
              PAPERLESS_OCR_LANGUAGE: eng
              # Configure user permissions
              USERMAP_GID: "65542" # gladius:external-services
              # Configure admin user
              PAPERLESS_ADMIN_USER:
                valueFrom:
                  secretKeyRef:
                    name: paperless-secret
                    key: PAPERLESS_ADMIN_USER
              PAPERLESS_ADMIN_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: paperless-secret
                    key: PAPERLESS_ADMIN_PASSWORD
              PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect
              PAPERLESS_DISABLE_REGULAR_LOGIN: false
              PAPERLESS_REDIRECT_LOGIN_TO_SSO: true
              SECRET_PAPERLESS_NGX_OAUTH_CLIENT_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: paperless-secret
                    key: PAPERLESS_OAUTH_CLIENT_SECRET
              PAPERLESS_SOCIALACCOUNT_PROVIDERS: |
                {
                  "openid_connect": {
                    "SCOPE": ["openid", "profile", "email"],
                    "OAUTH_PKCE_ENABLED": true,
                    "APPS": [
                      {
                        "provider_id": "zitadel",
                        "name": "Zitadel",
                        "client_id": "306647277202637416",
                        "secret": "${SECRET_PAPERLESS_NGX_OAUTH_CLIENT_SECRET}",
                        "settings": {
                          "server_url": "https://sso.${SECRET_DOMAIN}",
                          "token_auth_method": "client_secret_basic"
                        }
                      }
                    ]
                  }
                }
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 25m
                memory: 2Gi
              limits:
                memory: 6Gi
    service:
      app:
        controller: paperless
        ports:
          http:
            port: 8000
    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.ktmb1.net
        className: "internal"
        hosts:
          - host: paperless.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    serviceAccount:
      create: true
      name: paperless

    persistence:
      data:
        existingClaim: paperless
        advancedMounts:
          paperless:
            app:
              - path: /data/local
      nas:
        type: nfs
        server:  ktmb1-g-srv-004.iot.ktmb1.net
        path: /data/nfs/apps/paperless
        advancedMounts:
          paperless:
            app:
              - path: /data/nas
