---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: multus
spec:
  interval: 30m
  chart:
    spec:
      chart: multus
      version: 5.0.7
      sourceRef:
        kind: HelmRepository
        name: angelnu
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    image:
      repository: ghcr.io/k8snetworkplumbingwg/multus-cni
      tag: v4.2.0-thick@sha256:42ccc54689ea3003d3b6c7decadd85b4e296c15d3ad736da48d7e0c768d1f538
      logLevel: error
    cni:
      image:
        repository: ghcr.io/angelnu/cni-plugins
        tag: 1.7.1@sha256:b364ff65695b6279803a6fc29d85e9cb8a09815b87b7302e752897a4ed1dab58
      logLevel: error
      paths:
        bin: /opt/cni/bin
        config: /etc/cni/net.d
    resources:
      requests:
        cpu: 10m
      limits:
        memory: 1024Mi
    hostPaths:
      netns: /var/run/netns
