apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:WE58hFalA3fHT3yBn85ON3W5ZmqaZSPeXNQt7VnyDPA=,iv:4MAKhb8soes6ift4OrdrosUHRvQTR1SLxezf+Q2CxHc=,tag:JGFeyBaWQ9mZsAncOo0rZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlz8mrty9s0u7z5we2ak4mjyc7srf7u8tp0xe8rc2u559fpe4ajsw5n5rs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHSDdSNDFVMmhXUFBHVm1Z
            MXJZSXh5S0N0aEpGVGhqZnA0MVZGYm1hdGlBCktaUTdENGhSbC91M2poQVg1aDBh
            VnVuYXF3TU9IZmNHNmxPcm1VWDJnUDAKLS0tIGFYeVF5SUVWT1UxYjk0eS9mV2di
            M1ltTm0rREpMVHJ2U25wRFNRZHgvR28K+IIXJmebMibTx9wGXiJore/nXTDq2X0V
            yZe2s/W1fyiM8DFf9kLyNHYAbyljc4rf7+XtSXk5v2fZlaws2+sM+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-22T00:55:18Z"
    mac: ENC[AES256_GCM,data:pK0rNHR0dka9AGXZBfgWZzwgo7cYVkK01URP+3SShGPnAd/CzIdVsqPWjBUOqvmHH9bDxuGcO9J85b0I1PJMV7e8kTpWA3ndzobJnwWOZHWhL4ZL5W9inKODin/IN5vW1S4HQUT+0CcupDvJoG1el3w7rWP1ab2svOZhVl0k6q4=,iv:w0kNu+w1BY4o+IEoh5OphWdqiTlbQV1sNZSrpkLkhS4=,tag:2OSoUNOIoDnpCzUEimKdKw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
