apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:eX0/itvSNn4ifI+nlWW4z1KyrT6VPtu1fF9UXumalJE=,iv:DVyMjs2hxDRwB7cIttbn8cILfsfPwDmF7l4XxKGrt1g=,tag:DP4B4Scl6vXp5BBFpaR54w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4ep3d9r4u4mfv9268ch7nqck3favp35mfg9rqggy26gnfh6653svjah5t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwd05LakdYOWFtcVd0UnI3
            dUs4cGMvNDk5QWNJcUlYdGNtZnZUSHV0Y1RFCmczbEg5NFJwMGtjOWZ3di9lQWRT
            VHdjdkt3ckkrZVdwSEhlVXVoSDFXbmMKLS0tIGFEVk5KZjhJSUhwUU1OcG1pcHB4
            eXZybW1iWjJSUWVRazh5bHd5WDUrQTgKiPpuL0Le/TNlI+Xg6/mMVn+UpN1yEWJm
            2C5MKUBpTILnnr3KVdIEdAVSdDg1cll1Mvu3lSSxbuSWaCQpvaBDWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-07T09:05:37Z"
    mac: ENC[AES256_GCM,data:Zcg+uLD4YmocEm5GO/6Ue7paCEqOZlLt3HQCUkzWn16A6LAaqk7f0aTTguR58sL1gDpvjWOfsAjutdVWQClvGNeM8rT6oWhrs4eZ7dh3LS2tj68moUrbxVwuBVWzt69lKdDwv0dqovvwB8JmrqUQWMGfUVAJoGoRw06SMg5Nkww=,iv:8ASZURTMkU7OlllP7/liA5cE+A8BT3e1QeycqzoL64g=,tag:WAfNeISNBdTTIj8E4ljE/Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
