apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:NTDJrEZCv1v5xHX43HG/C7FS3l7VfsNvq5fyAN6ej2I=,iv:LnlBRo5ZnW2Fn+cHF8fn4/+6IPUfLO/qc10Wx86ZeWw=,tag:f2RcHfjclAy7lu8x94mPTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4ep3d9r4u4mfv9268ch7nqck3favp35mfg9rqggy26gnfh6653svjah5t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxakd6T05PWmNsckF0cnVl
            VGYvUHkxdkpSdUpkRmV2WGU4dy92UWxHTnk4CmNyejF1bWs3bFhUcmJFZXAvMzND
            WktwK21yRi9NUDJQeEwzdUV3MmMwRFEKLS0tIGdNSDBCNkFZUUdFc3RSWW1rcWlp
            cGRieTIydEVHR1NQNXpwbFFVRTFqYkEKI7pyIGP7MXrnwXPlvzFCBcYLP85L0BMh
            mgTEeMp134ZXMQI66zZ9DyAextku6pq+ObuyVGaAMHagWdj5IJWP6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-10T02:19:27Z"
    mac: ENC[AES256_GCM,data:qbvlvKE1cz+dRBCGJCZ56qaN5646+iSZf4gjP3fRom+p34nGzXAPAeijuy7fpgpz5lfE4e1I3t256nfo0Me4Rqldwh9+XwD06f9ubX6i7/NFcDezFq1EhbvSIADPedXPUD25aXKx+A7aURYRjQSmEpd1RobNDsRLWzopm+Bmn24=,iv:Q79C79RhHJGg/ijEEwBMd2T/q5VuZPfMPTPrqho1By8=,tag:0Ehby7orDtvbav0GST85WQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
