---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant-external
  namespace: default
spec:
  type: ExternalName
  externalName: homeassistant.local
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeassistant-external
  namespace: default
spec:
  ingressClassBane: internal
  rules:
  - host: homeassistant.alexeym.net
    http:
      paths:
      - backend:
          service:
            name: homeassistant-external
            port:
              number: 443
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - homeassistant.alexeym.net
