---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant-external
  namespace: default
spec:
  type: ExternalName
  externalName: ktmb1-g-srv-002.iot.home.alexeym.net
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeassistant-external
  namespace: default
spec:
  ingressClassName: internal
  rules:
  - host: homeassistant.alexeym.net
    http:
      paths:
      - backend:
          service:
            name: homeassistant-external
            port:
              number: 8123
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - homeassistant.alexeym.net
