---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  refreshInterval: 4h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: homepage-secret
    template:
      engineVersion: v2
      data:
        ## Non Cluster resources
        HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: "{{ .CLOUDFLARE_ACCOUNT_ID }}"
        HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: "{{ .CLOUDFLARE_TUNNEL_ID }}"
        HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: "{{ .CLOUDFLARE_TUNNEL_API_TOKEN }}"
        HOMEPAGE_VAR_UNIFI_USERNAME: "{{ .UNIFI_HOMEPAGE_USERNAME }}"
        HOMEPAGE_VAR_UNIFI_PASSWORD: "{{ .UNIFI_HOMEPAGE_PASSWORD }}"
        ## Home
        HOMEPAGE_VAR_HASS_TOKEN: "{{ .HASS_HOMEPAGE_TOKEN }}"
        HOMEPAGE_VAR_HASS_LATITUDE: "{{ .HASS_LATITUDE }}"
        HOMEPAGE_VAR_HASS_LONGITUDE: "{{ .HASS_LONGITUDE }}"
  dataFrom:
    - extract:
        key: cloudflare
    - extract:
        key: grafana
    - extract:
        key: home-assistant
    - extract:
        key: unifi

