---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: sso
        group: applications
        url: https://dashboard.ktmb1.net
        interval: 1m
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: pushover
