---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: certificates
  namespace: default
spec:
  updatePolicy: Replace
  refreshInterval: 4h
  secretStoreRefs:
    - name: aws-ssm
      kind: ClusterSecretStore
  selector:
    secret:
      name: alexeym-net-production-tls
  template:
    data:
      tls.crt: "{{ .tls.crt }}"
      tls.key: "{{ .tls.key }}"
  data:
    - match:
        secretKey: tls.crt
        remoteRef:
          remoteKey: alexeym-net-production-tls
          property: tls.crt
    - match:
        secretKey: tls.key
        remoteRef:
          remoteKey: alexeym-net-production-tls
          property: tls.key
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: certificates-cluster
spec:
  externalSecretName: certificates-cluster
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
          - observability
  externalSecretSpec:
    refreshInterval: 4h
    secretStoreRef:
      name: aws-ssm
      kind: ClusterSecretStore
    target:
      name: certificates-cluster-secret
      creationPolicy: Owner
      template:
        type: kubernetes.io/tls
        data:
          tls.crt: "{{ .tls.crt | toString }}"
          tls.key: "{{ .tls.key | toString }}"
    data:
      - secretKey: tls.crt
        remoteRef:
          key: certificates
          property: tls.crt
      - secretKey: tls.key
        remoteRef:
          key: certificates
          property: tls.key
