apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: certificates-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: aws-ssm
      kind: ClusterSecretStore
  selector:
    secret:
      name: alexeym-net-production-tls
  data:
    - match:
        secretKey: tls.crt
        remoteRef:
          remoteKey: certificates
          property: cert
    - match:
       secretKey: tls.crt
       remoteRef:
         remoteKey: certificates
         property: key
