---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant
spec:
  refreshInterval: 4h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: home-assistant-secret
    template:
      engineVersion: v2
      data:
        HASS_ELEVATION: "{{ .HASS_ELEVATION }}"
        HASS_LATITUDE: "{{ .HASS_LATITUDE }}"
        HASS_LONGITUDE: "{{ .HASS_LONGITUDE }}"
        PASSWORD: "{{ .HASS_CODE_PASSWORD }}"
  dataFrom:
    - extract:
        key: home-assistant
