apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:ZAy3/1IOxuKv8oKAhqjmRLvXkJObQcTI1mqGDYyOx/5wqSJpvHMLMg==,iv:m/U0AungkwkA71XAFsI8l9gJGlKWdSZN3eQ/FHgBua4=,tag:DNnjXU65qIZqmWaE9cT+fw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4ep3d9r4u4mfv9268ch7nqck3favp35mfg9rqggy26gnfh6653svjah5t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNbU8xUkdBZUhGOU1jaGg0
            YzVFV1JCdkVSZ2lOL0wwNy9rSUx2OVVIcVEwCnJQcU42Z1JRcEVGOUZUdW5HS2R5
            TytKR3lWOENDMTZYYmFhU0ZyN2l6YmMKLS0tIFZYZG5OQ0Nyako0c1FDd2N3d25q
            c09QSGJWQkg2QWQzaUxrYjFPTmQzUHcKax/Uq5lWzC+Oply3KVr3wtwzdO1UmMv7
            x/LrgtowxeEzrjdzPpzLWsD/2Wa1l4N+b/uqjfquIFmu26TkaW556w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-09T04:17:33Z"
    mac: ENC[AES256_GCM,data:UzmzY8WAoprkrFwHyuHgxwiY0jUh2bw9DDob2bSvstCic+gkREj8MGNI4WxxQykrKaxd+5thaQ/FYPYDXYcWISFtLtKYPhArB2QkpCBMPHspHgaU8wJukns7N7YflBwVmY/2DZS7qrZ+kzbfLiTRRNU2m4iatPafGgRm5BWNDyA=,iv:939ZOTPG+y6Aasql3/wl8NeCmUfGXV7LYgm94c3fiSI=,tag:bTNs9awUTGXzJQSlK5fDfQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
