apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:znYpVvSS+XECBMvvx8Kp91OE36IwXgxt77xanztNF/HtM/j/hXnxGA==,iv:K4xA5UDWwXnEqjELznE8yq3NhnJ1VbRLhZivV6wfWvc=,tag:aVTC9QtdJb98mlxe+ttdfA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4ep3d9r4u4mfv9268ch7nqck3favp35mfg9rqggy26gnfh6653svjah5t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYTVFOU56MzFQakJhSWVK
            YXlBTmJzM1hKb2hGOTZROVFVRFJ0ZUVrN3owCkhSMEl6aXhySHdxYmQvcmRJTm9Y
            NmVnc012M1NpNEpQdEdkTzRCV2ZZRHMKLS0tIE9BTjBPcDhENko1eWZvQWlZVDNk
            aE1BR3JUMThBQkpLQk1tYU5qeXExcjgKtLWKbJLMogQjpQhSBbfuEPiEqMRnLttx
            9GL+Vs8gOT+IiOLUHLjNEA55Ca2z12c29fGTfIDoMTYQQ6wBcyfdHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-07T03:34:30Z"
    mac: ENC[AES256_GCM,data:iWkUVetA1I0Y+eXPI98GxyOwDClQUTQthjfG/O0ULfdykJVwj8XHsa6QUFnUVKoC9BqyRgEY4QrXYcZrWwIV83xs4JXfWMFR4D8tbmEXL0HDRDCAgjCYs/IJMId4F+ScXo5tAjgtK4m3a57UjXc62zwFZ3r4Kyia8qP53RfVRlQ=,iv:3RnbvnElUw2C6FRiUqntPqy2UYC0ShlRUHRNZaniFOw=,tag:J6mjgyBdJTi/iZLDPc1rng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
