apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:yMN+Zw1xfyCNhnevDZ+G5RHSUX+EZPF+em7pwB+qm68Su3TOHu/qkA==,iv:KPY2qUGoRrwP/3H/2eOpPyTXzR7VEHGPrjBreXFw11A=,tag:Nf0aY76/+zxDoMeAYyUrbg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4ep3d9r4u4mfv9268ch7nqck3favp35mfg9rqggy26gnfh6653svjah5t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5TkpWVktTSXAxL0hGVzBk
            ZVVTNFBNWG5ZSCsxblFUWjlvUFF4a09xRWt3ClpJTjdXTzNHNFpNQnZTU3VsZDVV
            NlNONFdQNm9BUmNWNlMwQm0wNUtQYjgKLS0tIGt0TmViU3AyTDdpZWNCTVFjbWxN
            S3U2amxtczRWMHpIbDN1eUlmYXl5S3MKL5ETk2Zvgc/d7yISLpOVhK3FIK9aul9Q
            VdE2t1WJ8Bum41GGl1HPKomnDHiNDR6tXk9QzVhwo0uGkbZEAE/gVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-09T04:21:46Z"
    mac: ENC[AES256_GCM,data:J1fLPv4X4J6tq+W/cnLGkMt5695OmAy8n/JF5SuEI+7z1HOUK6qrk4ZY8+w9xbwWCcaN5h0BVeuImt/7D4IdGSaHdxBN7eJOPGJSefD0prddBZd6tMLI+JvE2szCli53W+SlbMsxF4MdsvEfsPmPvGYWqriLPphMh8EebkF9Nxc=,iv:VK8xiy62+ab8S7visHrb9Hl1dR2l5VUVo0WpwekV2Ro=,tag:Zc4nGeZc1dgDH16zI/6VRw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
