---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
spec:
  interval: 30m
  chart:
    spec:
      chart: redis
      version: 21.2.3
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: redis-secret
      valuesKey: redis_password
      targetPath: global.redis.password
    - kind: Secret
      name: redis-secret
      valuesKey: redis_password
      targetPath: auth.password
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    auth:
      enabled: true
      sentinel: false
    master:
      persistence:
        enabled: false
    replica:
      persistence:
        enabled: false
    sentinel:
      enabled: true
      masterSet: redis-master
      getMasterTimeout: 10
      startupProbe:
        enabled: false
        failureThreshold: 2
      persistence:
        enabled: false
      redisShutdownWaitFailover: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        interval: 1m

