---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: evcc-config
spec:
  refreshInterval: 4h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  data:
    - secretKey: MQTT_USERNAME
      remoteRef:
        key: emqx
        property: X_EMQX_MQTT_USERNAME
    - secretKey: MQTT_PASSWORD
      remoteRef:
        key: emqx
        property: X_EMQX_MQTT_PASSWORD
    - secretKey: TESLA_VIN
      remoteRef:
        key: teslamate
        property: TESLA_JULIE_VIN
  target:
    name: evcc-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        evcc.yaml: |-
          mqtt:
            broker: emqx-listeners.database.svc.cluster.local
            topic: evcc
            user: {{.MQTT_USERNAME}}
            password: {{.MQTT_PASSWORD}}

          circuits:
            - name: main
              title: Main circuit
              maxCurrent: 20
              maxPower: 14000

          vehicles:
            - name: julie
              type: custom
              title: "Julie"
              icon: car
              capacity: 80

              # From Teslamate
              soc: # battery soc (%)
                source: mqtt
                topic: teslamate/cars/1/battery_level
                timeout: 720h # 30d

              status:
                source: combined
                plugged:
                  source: mqtt
                  topic: teslamate/cars/1/plugged_in
                  timeout: 720h # 30d
                charging:
                  source: mqtt
                  topic: teslamate/cars/1/charger_actual_current
                  jq: if . > 0 then 1 else 0 end
                  timeout: 720h # 30d

              range: # optional electric range (km)
                source: mqtt
                topic: teslamate/cars/1/rated_battery_range_km
                timeout: 720h # 30d

              odometer: # optional odometer (km)
                source: mqtt
                topic: teslamate/cars/1/odometer
                timeout: 720h # 30d

              limitsoc: # optional in-vehicle limit soc, read-only (%)
                source: mqtt
                topic: teslamate/cars/1/charge_limit_soc
                timeout: 720h # 30d

              climater: # optional climate status (true/false)
                source: mqtt
                topic: teslamate/cars/1/is_climate_on
                timeout: 720h # 30d

              getMaxCurrent:
                source: mqtt
                topic: teslamate/cars/1/charge_current_request
                timeout: 720h # 30d

              chargeEnable: # optional charge enable (true/false)
                source: mqtt
                topic: tesla_ble/{{.TESLA_VIN}}/charging
                jq: if . == "true" then "start" elif . == "false" then "stop" else . end

              wakeup: # optional vehicle wake up command
                source: mqtt
                topic: tesla_ble/{{.TESLA_VIN}}/command
                payload: "wake"

              maxcurrent: # set charger max current (A)
                source: mqtt
                topic: tesla_ble/{{.TESLA_VIN}}/charging-set-amps

          site:
            title: Home
            residualPower: 0
            maxGridSupplyWhileBatteryCharging: 0

          network:
            schema: http
            host: 0.0.0.0
            port: 7070

          interval: 30s
          telemetry: false

          log: info
          levels:
            site: debug
            lp-1: debug
            lp-2: debug
            cache: error
            db: error
