---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app evcc
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      evcc:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
         app:
            image:
              repository: docker.io/evcc/evcc
              tag: 0.203.2

            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false

            resources:
              requests:
                cpu: 100m
                memory: 500M
              limits:
                memory: 1000M
    service:
      app:
        controller: evcc
        ports:
          http:
            port: &port 7070
          tcp8887:
            enabled: true
            port: 8887
          udp7090:
            enabled: true
            port: 7090
            protocol: UDP
          udp9522:
            enabled: true
            port: 9522
            protocol: UDP

    ingress:
      app:
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.ktmb1.net
        hosts:
          - host: evcc.ktmb1.net
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http

    persistence:
      config-file:
        type: secret
        name: evcc-config
        globalMounts:
          - path: /etc/evcc.yaml
            subPath: evcc.yaml

      config:
        existingClaim: "${VOLSYNC_CLAIM}"
        advancedMounts:
          evcc:
            app:
              - path: /root/.evcc
