apiVersion: v1
kind: Secret
metadata:
  name: aws-ssm-auth
stringData:
  access-key: ENC[AES256_GCM,data:tAeFY1Jb6gXz6iwukHq+ZJfAim8=,iv:un6fpGYdzObKZwfJYTgR4bUv+1vecAOhOwPPLfPSx5s=,tag:+/ClsWmqGDbDhvGAYWpepA==,type:str]
  secret-key: ENC[AES256_GCM,data:XG/fp9+3CR4sODFJhPqPN6OL52uzfXsKrQtgm3wgGTTdD2uCh5BJVw==,iv:xTyPhuxC2IpTiU6WOH5oD09prhtW7jjABjlbDF1KTKs=,tag:jxaPp6OucNHuxfWoBe2InA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14maqe2lw00kmdc0z7ulr8al7gwwz4wxgyltn8pd7h897wtakk98qlztlpn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Y0dxdk15MDlXNXZyemhk
        bXprUDUrMlYzVExDSlJ0MU1BNzI5VXBJU1VjCnZvUStwTTg3S1hUVGIzeEhtN1Bm
        Q2JDYlV1SEZmeHdGZW5RQjZab2ZVbm8KLS0tIGNDNlFuNW92R3VQa2UwVitVeE5v
        N3dMaFJpaWZJMGszYmRrTzFlRmxuN2cKMDKFw1yPlq3fDMXQ0Z153cYHn1d/cf/Y
        HC0Hr4ypo1NfjvQp6SjQeXNNPLai/6nFpDUaPBFaWuz4xAGJJ5WN8Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-10T11:41:41Z"
  mac: ENC[AES256_GCM,data:1pY2yhRwRlxhipqLmFSWjcxTPGHQlIrKTDyaVIKi9eKUlXwQlvmTOWnoG964VGWt10Gogxfnras8sIrbs6KJsG7SVFCxViw31sq+Ns2sA4X5hdfNCc6jAI2SiYSe6rA5PFRred0w/v9AAYcP6mNfqmPq3tlay5y9r2iLSq+J9x0=,iv:pfAoFbcGL1+jaxgN++ySQQ+q6WamCQejfHNu8C/a4gc=,tag:EeQO8PMkVxc4JfLi6TpDgA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
