apiVersion: v1
kind: Secret
metadata:
    name: aws-ssm-auth
stringData:
    access-key: ENC[AES256_GCM,data:aDwzMQIHHd4L5jeDQth1ihDzuh4=,iv:UhFk7gpO6LCtAnD9vDd305iKV/7CQPJftDxWSN0CfQA=,tag:p+w8E+3CwIo9n5nJ7tSxXA==,type:str]
    secret-key: ENC[AES256_GCM,data:DC26J1gdKCQcQjNGfkO8U9WVUlQLNC1In6JoSovNN0ollD5TOdHGOQ==,iv:N91kyUzg6t0oB/bLtKODSaix+vtsOMYaC2UXROkud78=,tag:a1CU/Fu/aKxuPSe6t40CTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlz8mrty9s0u7z5we2ak4mjyc7srf7u8tp0xe8rc2u559fpe4ajsw5n5rs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WUdlb0FOd1J3cUF5T2FC
            V2hreDhqYjNFOHBKNVFrbDR6NCtXUG5kNlFrCllETkFCcmRoZzRKSlhsbW5UdUd3
            QmlHSk5IRFdYa2hyNlpaTHkwQzFvMnMKLS0tIG1vNTNOUUZSMlpZZzZvdkhxRGRQ
            UTVHRVExbGVCNGFTeS9DTFR0dVhFdFkKRZW6//dKInXGsRrwoBGgsQbs4ThWYcoy
            TK0DhCzfX1gjMhLzH+wHx3pApEQCSHH7abX6UFOt5oPA9Yi+T8F1+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-18T22:12:46Z"
    mac: ENC[AES256_GCM,data:kXk9kRNnGQgOiqUi6Fk45M3vSdbE2ZDQ9tRJKKY4tUP/c4yj+dJXOh2wy0WQdMNaMHkR/aACa4xANR1NL4AWN7vm1kWlj2ulqG6psCOv1wCJOZRKudYWSLYr7ksvgh89yKNKqb2hHROQRUbGKbZP1ojImbB1Qdu4yzHPyWDVKiM=,iv:poWP+TlPtSuIFYdbqNSaxmC72zhs+wtlEnpplOUifzA=,tag:MzemcL0Z9AeRvTCDmahqwA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
