apiVersion: v1
kind: Secret
metadata:
    name: aws-ssm-auth
    namespace: external-secrets
stringData:
    access-key: ENC[AES256_GCM,data:m/AuTrNXuMJR9u7V+pKEM2mG4Ls=,iv:yelUyj7htwgKhPeZ0QUxqO3taHJf9XJpdGQNq2PU9tY=,tag:SWdYB5OxcgFPHxJrjDNLPg==,type:str]
    secret-key: ENC[AES256_GCM,data:cglA5vguk8T8CSTMHW+au3tnI3XsAARTShCP/UkHssR2vNi9LEavvA==,iv:t+se1oSKHcTaMPtdv+M3RJRwyi+WTOgfNszzjXQuJ/c=,tag:3E0GQ5vblCAg7WN3NL6b9A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kucqfw6vumv340793sefaungvzxresjtwhqk5vz3czlmaprfeejq58mvhj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4aUpxbENLdXJIbExwS3FG
            MERyQVV6K3VpaFlXRG1ZZy9jK2FUZkRZUDNvCkVTdHE1SmdFVFM3UFczNStaYUlU
            Rk5jNkJrRDkrTkMweDlxVnFaWjVubnMKLS0tIG94Wndxd2xtdllXTmVUYjhYeGRS
            NTFSK3doOE5aSDAwby9WME45VHYxUzgKQSvv/sdiERHfrZMTJRF6Hb369D+fcfgG
            urKrckoGx9oWyx1Tp47zUt3cb2TUckOjI7VBlqGnf7TpxQNqSb6eLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-18T21:54:17Z"
    mac: ENC[AES256_GCM,data:qsWkjRYH9jV7CRslodO+lkAXAzd3wyrj7h6nYuITID1GMEvK/5pEn/xjlN4D4OBfac/VXE0rRf9Q1hgPrOm9Iq0oZMGUaNtF5tcaNEQ0Xe5lCJxAw96W2AofGwCJud+i0I4Z4bODmsmOhyPfXsL45NgtG45gCbqze47Ule18R4I=,iv:0/cx+C0D9TbGzWtpSEfRdzvjcJjItQtYE/1iYOWD0I8=,tag:Shl2D5nkzM0I2jKhC/HkcQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
