---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app teslamate
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 17
              pullPolicy: Always
            envFrom:
              - secretRef:
                  name: teslamate-secret
        containers:
          main:
            image:
              repository: teslamate/teslamate
              tag: 2.0.0@sha256:e69b7155b8af81b0cdbcdc5e465292a9b8df5cf578bdb1d880666c9928dd7707
            env:
              TZ: "Australia/Sydney"
              DISABLE_MQTT: "true"
            envFrom:
              - secretRef:
                  name: teslamate-secret
    service:
      main:
        controller: main
        type: ClusterIP
        ports:
          http:
            port: 4000
    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.ktmb1.net
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http

