apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: open-webui
spec:
  refreshInterval: 4h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: open-webui-secret
    template:
      engineVersion: v2
      data:
        WEBUI_SECRET_KEY: "{{ .OPEN_WEBUI_SECRET_KEY }}"

  dataFrom:
    - extract:
        key: open-webui
