---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app open-webui
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: open-webui
      version: 5.4.0
      sourceRef:
        kind: HelmRepository
        name: *app
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: vllm
      namespace: ai
    - name: volsync
      namespace: volsync-system

  values:
    annotations:
      reloader.stakater.com/auto: "true"
    copyAppData:
      resources: {}
    ollama:
      enabled: false
    pipelines:
      enabled: true
      persistence:
        existingClaim: open-webui-pipelines
    tika:
      enabled: true

    extraEnvVars:
      - name: ENABLE_OPENAI_API
        value: "true"
      - name: OPENAI_API_KEY
        value: "EMPTY"
      - name: OPENAI_API_BASE_URL
        value: "http://vllm-router-service.ai.svc.cluster.local/v1"
      - name: DATABASE_URL
        valueFrom:
          secretKeyRef:
            name: open-webui-secret
            key: DATABASE_URL

      # - name: OAUTH_PROVIDER_NAME
      #   value: authentik
      # - name: ENABLE_OAUTH_SIGNUP
      #   value: "true"
      # - name: OPENID_PROVIDER_URL
      #   valueFrom:
      #     secretKeyRef:
      #       name: *app
      #       key: OPENID_PROVIDER_URL
      # - name: OAUTH_CLIENT_ID
      #   valueFrom:
      #     secretKeyRef:
      #       name: *app
      #       key: OAUTH_CLIENT_ID
      # - name: OAUTH_CLIENT_SECRET
      #   valueFrom:
      #     secretKeyRef:
      #       name: *app
      #       key: OAUTH_CLIENT_SECRET
      - name: WEBUI_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: open-webui-secret
            key: WEBUI_SECRET_KEY
      # - name: OPENAI_API_KEY
      #   valueFrom:
      #     secretKeyRef:
      #       name: *app
      #       key: OPENAI_API_KEY
    ingress:
      enabled: true
      class: internal
      annotations:
        external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN}"
      host: chat.${SECRET_DOMAIN}
      tls: true
      existingSecret: ${SECRET_DOMAIN/./-}-production-tls
    persistence:
      enabled: true
      existingClaim: open-webui

