---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app open-webui
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: open-webui
      version: 6.4.0
      sourceRef:
        kind: HelmRepository
        name: *app
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: volsync
      namespace: volsync-system
  values:
    annotations:
      reloader.stakater.com/auto: "true"
    copyAppData:
      resources: {}
    ollama:
      enabled: false
    pipelines:
      enabled: false
      persistence:
        existingClaim: open-webui-pipelines
    tika:
      enabled: true
    extraEnvVars:
      - name: ENABLE_OPENAI_API
        value: true
      - name: OPENAI_API_BASE_URL
        value: https://openrouter.ai/api/v1
      - name: OPENAI_API_KEY
        valueFrom:
          secretKeyRef:
            name: open-webui-secret
            key: OPENAI_API_KEY
      - name: DATABASE_URL
        valueFrom:
          secretKeyRef:
            name: open-webui-secret
            key: DATABASE_URL
      - name: WEBUI_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: open-webui-secret
            key: WEBUI_SECRET_KEY
    ingress:
      enabled: true
      class: internal
      annotations:
        external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN}"
      host: chat.${SECRET_DOMAIN}
      tls: true
      existingSecret: ${SECRET_DOMAIN/./-}-production-tls
    persistence:
      enabled: true
      existingClaim: "${VOLSYNC_CLAIM}"

