---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-pipelines
  namespace: ai
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-block

