---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-pipelines
  namespace: ai
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui
  namespace: ai
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 10Gi

